import { useEffect, useRef, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Menu, Plus, Search, Bell, List, PanelLeftClose, Download, X, Check, Settings } from 'lucide-react';
import { CATEGORIES, addDays, blankEvent, blankTask, cancelPending, dateLabel, dayDiff, deadlineLabel, filteredEvents, seoulToday, shiftMonth, validateEvent, validDate, type Category, type Schedule, type Task } from './model';
import { useData } from './useData';
import { useCloudData } from './useCloudData';
import { cloudConfigured, cloudConfigIncomplete } from './firebase';
import { CloudSession, CloudAccount } from './CloudSession';
import type { User } from 'firebase/auth';
import { Editor, Modal } from './Editor';
import { Calendar } from './Calendar';
import { BackupDialog, NotificationsDialog } from './Panels';
export default function App() {
 return cloudConfigured ? <CloudSession>{user => <CloudCalendar key={user.uid} user={user}/>}</CloudSession> : <LocalCalendar/>;
}
function LocalCalendar() {
 const store = useData();
 return <>{cloudConfigIncomplete && <div className="error-banner" role="alert">Firebase 설정 네 가지 중 빠진 값이 있습니다. 현재는 브라우저 저장 모드입니다.</div>}<CalendarApp store={store}/></>;
}
function CloudCalendar({ user }: { user: User }) {
 const store = useCloudData(user.uid);
 return <><CloudAccount user={user} busy={store.busy} onError={store.setError}/>{store.ready ? <CalendarApp store={store}/> : <div className="cloud-gate"><section className="cloud-login"><h1>업무달력 연결</h1><p role={store.error ? 'alert' : 'status'}>{store.error || '클라우드 일정을 불러오고 있습니다…'}</p><p className="help">접근 권한 오류가 있으면 위 계정 정보의 UID를 Firestore 규칙에 입력해 주세요.</p><button onClick={store.retry}>다시 연결</button></section></div>}</>;
}
function CalendarApp({ store }: { store: ReturnType<typeof useData> }) {
 const { data, commit, error } = store; const [month, setMonth] = useState(seoulToday()); const [query, setQuery] = useState(''); const [categories, setCategories] = useState<Category[]>([...CATEGORIES]); const [incomplete, setIncomplete] = useState(false); const [side, setSide] = useState(() => window.innerWidth > 900); const [view, setView] = useState<'calendar' | 'list'>(() => window.innerWidth < 700 ? 'list' : 'calendar'); const [selected, setSelected] = useState<string | null>(null); const [editor, setEditor] = useState<Schedule | null>(null); const [modal, setModal] = useState<'backup' | 'notifications' | null>(null); const [dayView, setDayView] = useState<string | null>(null); const [deleting, setDeleting] = useState<'event' | 'task' | null>(null); const [toast, setToast] = useState(''); const [now, setNow] = useState(Date.now());
 const today = seoulToday(new Date(now)); const events = filteredEvents(data, query, categories, incomplete); const current = data.events.find(e => e.id === selected); const task = data.tasks.find(t => t.id === current?.taskId); const related = data.events.filter(e => e.taskId === task?.id).sort((a, b) => a.start.localeCompare(b.start)); const unread = data.notices.filter(n => !n.read).length;
 const monthEvents = events.filter(e => e.start.slice(0, 7) <= month.slice(0, 7) && e.end.slice(0, 7) >= month.slice(0, 7)).sort((a, b) => a.start.localeCompare(b.start) || a.startTime.localeCompare(b.startTime));
 useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); }, [toast]);
 useEffect(() => { const t = setInterval(() => setNow(Date.now()), 15000); return () => clearInterval(t); }, []);
 const latest = useRef({ data, query, categories, incomplete }); latest.current = { data, query, categories, incomplete };
 useEffect(() => { type ModelContext = { registerTool: (tool: Record<string, unknown>, options: { signal: AbortSignal }) => void | Promise<void> }; const context = (document as Document & { modelContext?: ModelContext }).modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController(); try { void Promise.resolve(context.registerTool({ name: 'list_calendar_events', title: '업무달력 일정 조회', description: '현재 검색·분류·준비할 일 필터에 해당하는 일정과 관련 업무를 조회합니다. 데이터는 변경하지 않습니다.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute: (input: unknown) => { if (!input || typeof input !== 'object' || Array.isArray(input) || Object.keys(input).length) throw new Error('빈 객체만 입력할 수 있습니다.'); const s = latest.current; return filteredEvents(s.data, s.query, s.categories, s.incomplete).map(e => ({ id: e.id, title: e.title, start: e.start, end: e.end, task: s.data.tasks.find(t => t.id === e.taskId)?.name })); } }, { signal: lifecycle.signal })).catch(() => {}); } catch { /* Optional browser API. */ } return () => lifecycle.abort(); }, []);
 function add(date = today, taskId = '') { setEditor({ ...blankEvent(date), taskId }); }
 function open(id: string) { setSelected(id); setDayView(null); }
 async function saveEvent(event: Schedule, changedTask: Task, inline = false) {
   const old = data.events.find(e => e.id === event.id); const nextEvent = { ...event, revision: (old?.revision ?? 0) + 1, reminderSince: Date.now() };
   let next = cancelPending(data, event.id); const tasks = next.tasks.some(t => t.id === changedTask.id) ? next.tasks.map(t => t.id === changedTask.id ? changedTask : t) : [...next.tasks, changedTask]; const allEvents = old ? next.events.map(e => e.id === event.id ? nextEvent : e) : [...next.events, nextEvent];
   next = { ...next, tasks: tasks.filter(t => allEvents.some(e => e.taskId === t.id)), events: allEvents };
   if (!await commit(next)) return false; if (!inline) { setSelected(event.id); setMonth(event.start); } setToast(old ? '일정을 수정했습니다.' : '일정을 저장했습니다.'); return true;
 }
 async function move(id: string, date: string, origin: string, resize: boolean) { const event = data.events.find(e => e.id === id); if (!event || !validDate(origin) || !validDate(date)) return; const delta = dayDiff(date, origin); const updated = resize ? { ...event, end: date } : { ...event, start: addDays(event.start, delta), end: addDays(event.end, delta) }; const problem = validateEvent(updated); if (problem) { setToast(problem); return; } if (await commit({ ...cancelPending(data, id), events: data.events.map(e => e.id === id ? { ...updated, revision: e.revision + 1, reminderSince: Date.now() } : e) })) setToast(resize ? `종료일을 ${dateLabel(date)}까지로 변경했습니다.` : '일정 날짜를 이동했습니다.'); }
 async function remove() { if (!current || !task) return; const ids = deleting === 'task' ? related.map(e => e.id) : [current.id]; const remaining = data.events.filter(e => !ids.includes(e.id)); const next = ids.reduce((result, id) => cancelPending(result, id), data); if (await commit({ ...next, events: remaining, tasks: data.tasks.filter(t => remaining.some(e => e.taskId === t.id)) })) { setDeleting(null); setSelected(null); setToast('삭제했습니다.'); } }
 const eventRows = (rows: Schedule[]) => rows.length ? <div className="event-list">{rows.map(e => { const t = data.tasks.find(t => t.id === e.taskId)!; const deadline = deadlineLabel(e, today, now); return <button key={e.id} className={`list-row cat-${CATEGORIES.indexOf(t.category)}`} onClick={() => open(e.id)}><span className="list-date"><strong>{dateLabel(e.start)}</strong><small>{e.start !== e.end ? `~ ${dateLabel(e.end)}` : e.allDay ? '종일' : `${e.startTime}–${e.endTime}`}</small></span><span className="list-main"><strong>{e.title}</strong><small>{t.name !== e.title ? `관련 업무 · ${t.name}` : e.start !== e.end ? '여러 날 일정' : '일정'}</small></span><span className="list-meta"><span className="tag">{t.category}</span>{deadline && <span className="deadline-badge">{deadline}</span>}</span><ChevronRight size={16}/></button>; })}</div> : <div className="empty-state"><CalendarDays size={30}/><p>표시할 일정이 없습니다.</p><small>다른 달을 보거나 검색어와 필터를 확인해 주세요.</small><button onClick={() => add(month.slice(0, 7) === today.slice(0, 7) ? today : month.slice(0, 7) + '-01')}><Plus size={16}/>일정 추가</button></div>;
 return <div className="app"><header className="topbar"><button className="icon-button menu-button" aria-label={side ? '필터 영역 접기' : '필터 영역 펼치기'} aria-expanded={side} onClick={() => setSide(!side)}><Menu size={20}/></button><div className="brand"><span className="brand-icon"><CalendarDays size={21}/></span>업무달력</div><span className="personal-label">개인 워크스페이스</span><div className="top-spacer"/><label className="search"><Search size={18}/><input aria-label="일정 검색" placeholder="일정, 업무, 메모 검색" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button className="icon-button" aria-label="검색 지우기" onClick={() => setQuery('')}><X size={14}/></button>}</label><button className={'icon-button notification-button ' + (unread ? 'has-unread' : '')} aria-label={`알림 ${unread}개 미확인`} onClick={() => setModal('notifications')}><Bell size={20}/>{unread > 0 && <span className="notification-count">{unread}</span>}</button><button className="primary add-button" onClick={() => add()}><Plus size={18}/><span>일정 추가</span></button></header>
 <div className="workspace">{side && <><button className="sidebar-scrim" aria-label="필터 닫기" onClick={() => setSide(false)}/><aside className="sidebar"><div className="sidebar-heading">내 캘린더<button className="icon-button" aria-label="사이드바 접기" onClick={() => setSide(false)}><PanelLeftClose size={17}/></button></div><button className="nav-active" onClick={() => { setQuery(''); setCategories([...CATEGORIES]); setIncomplete(false); setMonth(today); }}><CalendarDays size={18}/>업무달력</button><div className="section-label">분류</div>{CATEGORIES.map((c, i) => <label className="category-filter" key={c}><input type="checkbox" aria-label={c} checked={categories.includes(c)} onChange={() => setCategories(prev => prev.includes(c) ? prev.filter(x => x !== c) : [...prev, c])}/><span className={'category-dot cat-' + i}/>{c}<span className="count">{data.events.filter(e => data.tasks.find(t => t.id === e.taskId)?.category === c).length}</span></label>)}<div className="divider"/><label className="category-filter"><input type="checkbox" checked={incomplete} onChange={e => setIncomplete(e.target.checked)}/>준비할 일 남음</label><div className="sidebar-bottom"><button onClick={() => setModal('notifications')}><Settings size={17}/>알림 설정</button><button onClick={() => setModal('backup')}><Download size={17}/>백업 및 가져오기</button><small>{store.cloud ? "같은 계정으로 기기 간 동기화" : "이 브라우저에 자동 저장"}<br/>시간 기준 · 서울 (KST)</small></div></aside></>}
 <main><div className="calendar-toolbar"><div className="month-title"><h1>{month.slice(0, 4)}년 {Number(month.slice(5, 7))}월</h1><button className="icon-button" aria-label="이전 달" onClick={() => setMonth(shiftMonth(month, -1))}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="다음 달" onClick={() => setMonth(shiftMonth(month, 1))}><ChevronRight size={18}/></button><button onClick={() => setMonth(today)}>오늘</button></div><div className="view-toggle"><button aria-pressed={view === 'calendar'} className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}><CalendarDays size={16}/>월간</button><button aria-pressed={view === 'list'} className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={16}/>목록</button></div></div><div className="calendar-subtitle"><span>{query ? `‘${query}’ 검색 결과` : '일정과 준비할 일을 한곳에서'}</span><span>{monthEvents.length}개 일정{incomplete ? ' · 준비할 일 남음' : ''}</span></div>{error && <div className="error-banner" role="alert">{error}<button onClick={() => setModal('backup')}>백업 열기</button>{store.cloud && <button onClick={store.retry}>다시 연결</button>}</div>}{view === 'calendar' ? <div className="calendar-scroll"><Calendar data={data} events={events} month={month} open={open} quickAdd={async (title, start, end) => { const task = { ...blankTask(), name: title }; const event = { ...blankEvent(start), title, end, taskId: task.id, type: start === end ? "일반 일정" as const : "기간" as const }; return saveEvent(event, task, true); }} showDay={setDayView} move={move}/></div> : eventRows(monthEvents)}<footer><span><span className="status-dot"/>{error ? '저장 확인 필요' : store.storageLabel}</span><span>{view === 'calendar' ? '빈칸 클릭 후 바로 입력 · 날짜를 드래그해 기간 입력' : '일정을 눌러 자료와 준비할 일을 확인하세요'}</span></footer></main>
 {current && task && <Editor key={`${current.id}:${current.revision}`} mode="panel" data={data} event={current} onSave={saveEvent} onClose={() => setSelected(null)} onDelete={() => setDeleting('event')}/>}
 </div>{editor && <Editor key={editor.id} data={data} event={editor} onSave={saveEvent} onClose={() => setEditor(null)}/>}{dayView && <Modal title={`${dateLabel(dayView)}의 일정`} onClose={() => setDayView(null)} wide><div className="modal-content">{eventRows(events.filter(e => e.start <= dayView && e.end >= dayView))}</div><div className="modal-actions"><button className="primary" onClick={() => { add(dayView); setDayView(null); }}><Plus size={16}/>이 날짜에 일정 추가</button></div></Modal>}
 {deleting && current && task && <Modal title={deleting === 'task' ? '업무 전체 삭제' : '일정 삭제'} onClose={() => setDeleting(null)}><div className="modal-content"><p><strong>{deleting === 'task' ? task.name : current.title}</strong></p><p className="help">{deleting === 'task' ? `연결된 일정 ${related.length}개와 업무의 메모·링크·체크리스트를 함께 삭제합니다.` : related.length > 1 ? '이 일정만 삭제합니다. 같은 업무의 다른 일정과 공통 자료는 유지됩니다.' : '마지막 연결 일정이므로 업무의 공통 자료도 함께 삭제됩니다.'} 이 작업은 되돌릴 수 없습니다.</p></div><div className="modal-actions"><button onClick={() => setDeleting(null)}>취소</button><button className="danger-solid" onClick={remove}>삭제</button></div></Modal>}
 {modal === 'backup' && <BackupDialog cloud={store.cloud} data={data} onClose={() => setModal(null)} commit={commit} toast={setToast} onImported={() => setSelected(null)}/>}
 {modal === 'notifications' && <NotificationsDialog data={data} commit={commit} onClose={() => setModal(null)} onOpen={open} onTest={e => { setModal(null); setEditor(e); }} toast={setToast}/>}
 {toast && <div className="toast" role="status"><Check size={17}/>{toast}<button className="icon-button" aria-label="안내 닫기" onClick={() => setToast('')}><X size={15}/></button></div>}
 </div>;
}

