import { useEffect, useRef, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Menu, Plus, Search, Bell, List, PanelLeftClose, Download, X, Check, Settings, SlidersHorizontal, ListTodo } from 'lucide-react';
import { addDays, blankEvent, blankTask, cancelPending, dateLabel, dayDiff, deadlineLabel, filteredEvents, searchEvents, seoulToday, shiftMonth, validateEvent, validDate, calendarVars, categoryStyleOf, defaultSettings, fallbackCategory, schoolHolidayOn, type Category, type Schedule, type Settings as SettingsData, type Task } from './model';
import { useData } from './useData';
import { useCloudData } from './useCloudData';
import { cloudConfigured, cloudConfigIncomplete } from './firebase';
import { CloudSession, CloudAccount } from './CloudSession';
import type { User } from 'firebase/auth';
import { Editor, Modal } from './Editor';
import { Calendar } from './Calendar';
import { BackupDialog } from './Panels';
import { SettingsDialog, type SettingsTab } from './Settings';
import { TodoDialog } from './Todo';
import { SharedCalendar, rememberShare, rememberedShare } from './Shared';
import { useHolidays } from './holidays';
export default function App() {
 const [viewing, setViewing] = useState(rememberedShare);
 const openShare = (code: string) => { rememberShare(code); setViewing(code); };
 if (viewing) return <SharedCalendar code={viewing} onLeave={() => setViewing('')}/>;
 return cloudConfigured ? <CloudSession>{user => <CloudCalendar key={user.uid} user={user} onViewShare={openShare}/>}</CloudSession> : <LocalCalendar onViewShare={openShare}/>;
}
function LocalCalendar({ onViewShare }: { onViewShare: (code: string) => void }) {
 const store = useData();
 return <>{cloudConfigIncomplete && <div className="error-banner" role="alert">Firebase 설정 네 가지 중 빠진 값이 있습니다. 현재는 브라우저 저장 모드입니다.</div>}<CalendarApp store={store} onViewShare={onViewShare}/></>;
}
function CloudCalendar({ user, onViewShare }: { user: User; onViewShare: (code: string) => void }) {
 const store = useCloudData(user.uid);
 return <><CloudAccount user={user} busy={store.busy} onError={store.setError}/>{store.ready ? <CalendarApp store={store} onViewShare={onViewShare}/> : <div className="cloud-gate"><section className="cloud-login"><h1>업무달력 연결</h1><p role={store.error ? 'alert' : 'status'}>{store.error || '클라우드 일정을 불러오고 있습니다…'}</p><p className="help">접근 권한 오류가 있으면 위 계정 정보의 UID를 Firestore 규칙에 입력해 주세요.</p><button onClick={store.retry}>다시 연결</button></section></div>}</>;
}
function CalendarApp({ store, onViewShare }: { store: ReturnType<typeof useData>; onViewShare: (code: string) => void }) {
 const { data, commit, error } = store; const [month, setMonth] = useState(seoulToday()); const [query, setQuery] = useState(''); const settings = data.settings ?? defaultSettings(); const categoryNames = settings.categories.map(c => c.name); const [categories, setCategories] = useState<Category[]>(() => [...categoryNames]); const [incomplete, setIncomplete] = useState(false); const [side, setSide] = useState(() => window.innerWidth > 900); const [view, setView] = useState<'calendar' | 'list'>(() => { const pick = store.data.settings?.calendar?.defaultView ?? 'auto'; return pick === 'auto' ? (window.innerWidth < 700 ? 'list' : 'calendar') : pick; }); const [selected, setSelected] = useState<string | null>(null); const [editor, setEditor] = useState<Schedule | null>(null); const [modal, setModal] = useState<'backup' | 'settings' | 'todo' | null>(null); const [dayView, setDayView] = useState<string | null>(null); const [deleting, setDeleting] = useState<'event' | 'task' | null>(null); const [toast, setToast] = useState(''); const [settingsTab, setSettingsTab] = useState<SettingsTab>('profile'); const [searchOpen, setSearchOpen] = useState(false); const [highlight, setHighlight] = useState(0); const [now, setNow] = useState(Date.now());
 const today = seoulToday(new Date(now)); const events = filteredEvents(data, '', categories, incomplete);
 const search = searchEvents(data, query, today); const current = data.events.find(e => e.id === selected); const task = data.tasks.find(t => t.id === current?.taskId); const related = data.events.filter(e => e.taskId === task?.id).sort((a, b) => a.start.localeCompare(b.start)); const unread = data.notices.filter(n => !n.read).length;
 const openTodos = (data.todos ?? []).filter(t => !t.done).length;
 const allChecked = categoryNames.length > 0 && categoryNames.every(name => categories.includes(name)); const someChecked = categoryNames.some(name => categories.includes(name));
 const gridYears = [Number(month.slice(0, 4)) - 1, Number(month.slice(0, 4)), Number(month.slice(0, 4)) + 1];
 const { holidays } = useHolidays(gridYears, settings.holidayKey);
 const monthEvents = events.filter(e => e.start.slice(0, 7) <= month.slice(0, 7) && e.end.slice(0, 7) >= month.slice(0, 7)).sort((a, b) => a.start.localeCompare(b.start) || a.startTime.localeCompare(b.startTime));
 useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); }, [toast]);
 useEffect(() => { const t = setInterval(() => setNow(Date.now()), 15000); return () => clearInterval(t); }, []);
 const latest = useRef({ data, query, categories, incomplete }); latest.current = { data, query, categories, incomplete };
 useEffect(() => { type ModelContext = { registerTool: (tool: Record<string, unknown>, options: { signal: AbortSignal }) => void | Promise<void> }; const context = (document as Document & { modelContext?: ModelContext }).modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController(); try { void Promise.resolve(context.registerTool({ name: 'list_calendar_events', title: '업무달력 일정 조회', description: '현재 검색·분류·준비할 일 필터에 해당하는 일정과 관련 업무를 조회합니다. 데이터는 변경하지 않습니다.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute: (input: unknown) => { if (!input || typeof input !== 'object' || Array.isArray(input) || Object.keys(input).length) throw new Error('빈 객체만 입력할 수 있습니다.'); const s = latest.current; return filteredEvents(s.data, s.query, s.categories, s.incomplete).map(e => ({ id: e.id, title: e.title, start: e.start, end: e.end, task: s.data.tasks.find(t => t.id === e.taskId)?.name })); } }, { signal: lifecycle.signal })).catch(() => {}); } catch { /* Optional browser API. */ } return () => lifecycle.abort(); }, []);
 function add(date = today, taskId = '') { setEditor({ ...blankEvent(date), taskId }); }
 function open(id: string) { setSelected(id); setDayView(null); }
 function jumpTo(event: Schedule) {
   const category = data.tasks.find(t => t.id === event.taskId)?.category;
   if (category && !categories.includes(category)) setCategories(previous => [...previous, category]);
   setMonth(event.start); setSelected(event.id); setDayView(null); setSearchOpen(false); setHighlight(0);
 }
 function searchKeys(e: React.KeyboardEvent) {
   if (!search.rows.length) { if (e.key === 'Escape') { setQuery(''); setSearchOpen(false); } return; }
   if (e.key === 'ArrowDown') { e.preventDefault(); setSearchOpen(true); setHighlight(h => (h + 1) % search.rows.length); }
   else if (e.key === 'ArrowUp') { e.preventDefault(); setHighlight(h => (h - 1 + search.rows.length) % search.rows.length); }
   else if (e.key === 'Enter') { e.preventDefault(); jumpTo(search.rows[Math.min(highlight, search.rows.length - 1)]); }
   else if (e.key === 'Escape') { setSearchOpen(false); }
 }
 async function saveEvent(event: Schedule, changedTask: Task, inline = false) {
   const old = data.events.find(e => e.id === event.id); const nextEvent = { ...event, revision: (old?.revision ?? 0) + 1, reminderSince: Date.now() };
   let next = cancelPending(data, event.id); const tasks = next.tasks.some(t => t.id === changedTask.id) ? next.tasks.map(t => t.id === changedTask.id ? changedTask : t) : [...next.tasks, changedTask]; const allEvents = old ? next.events.map(e => e.id === event.id ? nextEvent : e) : [...next.events, nextEvent];
   next = { ...next, tasks: tasks.filter(t => allEvents.some(e => e.taskId === t.id)), events: allEvents };
   if (!await commit(next)) return false; if (!inline) { setSelected(event.id); setMonth(event.start); } setToast(old ? '일정을 수정했습니다.' : '일정을 저장했습니다.'); return true;
 }
 async function move(id: string, date: string, origin: string, resize: boolean) { const event = data.events.find(e => e.id === id); if (!event || !validDate(origin) || !validDate(date)) return; const delta = dayDiff(date, origin); const updated = resize ? { ...event, end: date } : { ...event, start: addDays(event.start, delta), end: addDays(event.end, delta) }; const problem = validateEvent(updated); if (problem) { setToast(problem); return; } if (await commit({ ...cancelPending(data, id), events: data.events.map(e => e.id === id ? { ...updated, revision: e.revision + 1, reminderSince: Date.now() } : e) })) setToast(resize ? `종료일을 ${dateLabel(date)}까지로 변경했습니다.` : '일정 날짜를 이동했습니다.'); }
 async function saveSettings(next: SettingsData, renames: Record<string, string>) {
   const rename = (name: string) => renames[name] ?? name;
   const known = new Set(next.categories.map(c => c.name));
   const fallback = next.categories.find(c => c.name === '미지정')?.name ?? next.categories[0].name;
   const tasks = data.tasks.map(t => { const moved = rename(t.category); return moved === t.category && known.has(t.category) ? t : { ...t, category: known.has(moved) ? moved : fallback }; });
   if (!await commit({ ...data, tasks, settings: next })) return false;
   setCategories(previous => { const moved = previous.map(rename).filter(name => known.has(name)); const added = next.categories.map(c => c.name).filter(name => !data.settings.categories.some(c => rename(c.name) === name)); return [...new Set([...moved, ...added])]; });
   return true;
 }
 async function remove() { if (!current || !task) return; const ids = deleting === 'task' ? related.map(e => e.id) : [current.id]; const remaining = data.events.filter(e => !ids.includes(e.id)); const next = ids.reduce((result, id) => cancelPending(result, id), data); if (await commit({ ...next, events: remaining, tasks: data.tasks.filter(t => remaining.some(e => e.taskId === t.id)) })) { setDeleting(null); setSelected(null); setToast('삭제했습니다.'); } }
 const eventRows = (rows: Schedule[]) => rows.length ? <div className="event-list">{rows.map(e => { const t = data.tasks.find(t => t.id === e.taskId)!; const deadline = deadlineLabel(e, today, now); return <button key={e.id} className="list-row" style={categoryStyleOf(settings, t.category)} onClick={() => open(e.id)}><span className="list-date"><strong>{dateLabel(e.start)}</strong><small>{e.start !== e.end ? `~ ${dateLabel(e.end)}` : e.allDay ? '종일' : `${e.startTime}–${e.endTime}`}</small></span><span className="list-main"><strong>{e.title}</strong><small>{t.name !== e.title ? `관련 업무 · ${t.name}` : e.start !== e.end ? '여러 날 일정' : '일정'}</small></span><span className="list-meta"><span className="tag">{t.category}</span>{deadline && <span className="deadline-badge">{deadline}</span>}</span><ChevronRight size={16}/></button>; })}</div> : <div className="empty-state"><CalendarDays size={30}/><p>표시할 일정이 없습니다.</p><small>다른 달을 보거나 검색어와 필터를 확인해 주세요.</small><button onClick={() => add(month.slice(0, 7) === today.slice(0, 7) ? today : month.slice(0, 7) + '-01')}><Plus size={16}/>일정 추가</button></div>;
 return <div className="app" style={calendarVars(settings.calendar)}><header className="topbar"><button className="icon-button menu-button" aria-label={side ? '필터 영역 접기' : '필터 영역 펼치기'} aria-expanded={side} onClick={() => setSide(!side)}><Menu size={20}/></button><div className="brand"><span className="brand-icon"><CalendarDays size={21}/></span>업무달력</div>{settings.extras?.todo && <button className="icon-button extra-button" aria-label="할 일 목록" title="할 일 목록" onClick={() => setModal('todo')}><ListTodo size={19}/>{openTodos > 0 && <span className="extra-count">{openTodos}</span>}</button>}<span className="personal-label">개인 워크스페이스</span><div className="top-spacer"/><div className="search-box"><label className="search"><Search size={18}/><input aria-label="일정 검색" placeholder="일정, 업무, 메모 검색" autoComplete="off" role="combobox" aria-expanded={searchOpen && !!query.trim()} aria-controls="search-results" value={query} onChange={e => { setQuery(e.target.value); setSearchOpen(true); setHighlight(0); }} onFocus={() => setSearchOpen(true)} onBlur={() => window.setTimeout(() => setSearchOpen(false), 150)} onKeyDown={searchKeys}/>{query && <button className="icon-button" aria-label="검색 지우기" onClick={() => { setQuery(''); setSearchOpen(false); }}><X size={14}/></button>}</label>{searchOpen && !!query.trim() && <div className="search-results" id="search-results" role="listbox">{search.rows.map((e, index) => { const t = data.tasks.find(item => item.id === e.taskId)!; return <button key={e.id} role="option" aria-selected={index === highlight} className={'search-result ' + (index === highlight ? 'active' : '')} onMouseEnter={() => setHighlight(index)} onClick={() => jumpTo(e)}><span className="search-date"><strong>{dateLabel(e.start)}</strong>{e.start !== e.end ? ' ~ ' + dateLabel(e.end) : ''}</span><span className="search-main"><strong>{e.title}</strong><small>{t.name !== e.title ? t.name : e.allDay ? '종일' : e.startTime + '–' + e.endTime}</small></span><span className="tag" style={categoryStyleOf(settings, t.category)}>{t.category}</span></button>; })}{!search.rows.length && <p className="search-hint">‘{query.trim()}’와 맞는 일정이 없습니다.</p>}{search.total > search.rows.length && <p className="search-hint">{search.total}개 중 {search.rows.length}개를 보여 줍니다. 검색어를 더 입력해 보세요.</p>}</div>}</div><button className={'icon-button notification-button ' + (unread ? 'has-unread' : '')} aria-label={`알림 ${unread}개 미확인`} onClick={() => { setSettingsTab('notice'); setModal('settings'); }}><Bell size={20}/>{unread > 0 && <span className="notification-count">{unread}</span>}</button><button className="primary add-button" onClick={() => add()}><Plus size={18}/><span>일정 추가</span></button></header>
 <div className="workspace">{side && <><button className="sidebar-scrim" aria-label="필터 닫기" onClick={() => setSide(false)}/><aside className="sidebar"><div className="sidebar-heading"><button className="icon-button" aria-label="사이드바 접기" onClick={() => setSide(false)}><PanelLeftClose size={17}/></button></div><div className="section-label">분류</div><label className="category-filter filter-all"><input type="checkbox" aria-label="분류 전체 선택" checked={allChecked} ref={el => { if (el) el.indeterminate = !allChecked && someChecked; }} onChange={() => setCategories(allChecked ? [] : [...categoryNames])}/><span className="category-dot dot-all"/>전체<span className="count">{data.events.length}</span></label>{settings.categories.map(c => <label className="category-filter" key={c.id}><input type="checkbox" aria-label={c.name} checked={categories.includes(c.name)} onChange={() => setCategories(prev => prev.includes(c.name) ? prev.filter(x => x !== c.name) : [...prev, c.name])}/><span className="category-dot" style={categoryStyleOf(settings, c.name)}/>{c.name}<span className="count">{data.events.filter(e => data.tasks.find(t => t.id === e.taskId)?.category === c.name).length}</span></label>)}<div className="divider"/><label className="category-filter"><input type="checkbox" checked={incomplete} onChange={e => setIncomplete(e.target.checked)}/>준비할 일 남음</label><div className="sidebar-bottom"><button onClick={() => { setSettingsTab('profile'); setModal('settings'); }}><SlidersHorizontal size={17}/>설정</button><button onClick={() => { setSettingsTab('notice'); setModal('settings'); }}><Settings size={17}/>알림 설정</button><button onClick={() => setModal('backup')}><Download size={17}/>백업 및 가져오기</button><small>{store.cloud ? "같은 계정으로 기기 간 동기화" : "이 브라우저에 자동 저장"}<br/>시간 기준 · 서울 (KST)</small></div></aside></>}
 <main><div className="calendar-toolbar"><div className="month-title"><h1>{month.slice(0, 4)}년 {Number(month.slice(5, 7))}월</h1><button className="icon-button" aria-label="이전 달" onClick={() => setMonth(shiftMonth(month, -1))}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="다음 달" onClick={() => setMonth(shiftMonth(month, 1))}><ChevronRight size={18}/></button><button onClick={() => setMonth(today)}>오늘</button></div><div className="view-toggle"><button aria-pressed={view === 'calendar'} className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}><CalendarDays size={16}/>월간</button><button aria-pressed={view === 'list'} className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={16}/>목록</button></div></div><div className="calendar-subtitle"><span>일정과 준비할 일을 한곳에서</span><span>{monthEvents.length}개 일정{incomplete ? ' · 준비할 일 남음' : ''}</span></div>{error && <div className="error-banner" role="alert">{error}<button onClick={() => setModal('backup')}>백업 열기</button>{store.cloud && <button onClick={store.retry}>다시 연결</button>}</div>}{view === 'calendar' ? <div className="calendar-scroll"><Calendar data={data} settings={settings} holidays={holidays} events={events} month={month} open={open} quickAdd={async (title, start, end) => { const task = { ...blankTask(fallbackCategory(settings)), name: title }; const event = { ...blankEvent(start), title, end, taskId: task.id, type: start === end ? "일반 일정" as const : "기간" as const }; return saveEvent(event, task, true); }} showDay={setDayView} move={move}/></div> : eventRows(monthEvents)}<footer><span><span className="status-dot"/>{error ? '저장 확인 필요' : store.storageLabel}</span><span>{view === 'calendar' ? '빈칸 클릭 후 바로 입력 · 날짜를 드래그해 기간 입력' : '일정을 눌러 자료와 준비할 일을 확인하세요'}</span></footer></main>
 {current && task && <Editor key={`${current.id}:${current.revision}`} mode="panel" data={data} event={current} onSave={saveEvent} onClose={() => setSelected(null)} onDelete={() => setDeleting('event')}/>}
 </div>{editor && <Editor key={editor.id} data={data} event={editor} onSave={saveEvent} onClose={() => setEditor(null)}/>}{dayView && <Modal title={`${dateLabel(dayView)}의 일정`} onClose={() => setDayView(null)} wide><div className="modal-content">{eventRows(events.filter(e => e.start <= dayView && e.end >= dayView))}</div><div className="modal-actions"><button className="primary" onClick={() => { add(dayView); setDayView(null); }}><Plus size={16}/>이 날짜에 일정 추가</button></div></Modal>}
 {deleting && current && task && <Modal title={deleting === 'task' ? '업무 전체 삭제' : '일정 삭제'} onClose={() => setDeleting(null)}><div className="modal-content"><p><strong>{deleting === 'task' ? task.name : current.title}</strong></p><p className="help">{deleting === 'task' ? `연결된 일정 ${related.length}개와 업무의 메모·링크·체크리스트를 함께 삭제합니다.` : related.length > 1 ? '이 일정만 삭제합니다. 같은 업무의 다른 일정과 공통 자료는 유지됩니다.' : '마지막 연결 일정이므로 업무의 공통 자료도 함께 삭제됩니다.'} 이 작업은 되돌릴 수 없습니다.</p></div><div className="modal-actions"><button onClick={() => setDeleting(null)}>취소</button><button className="danger-solid" onClick={remove}>삭제</button></div></Modal>}
 {modal === 'backup' && <BackupDialog cloud={store.cloud} data={data} onClose={() => setModal(null)} commit={commit} toast={setToast} onImported={() => setSelected(null)}/>}
 {modal === 'todo' && <TodoDialog data={data} onClose={() => setModal(null)} commit={commit} toast={setToast}/>}
 {modal === 'settings' && <SettingsDialog data={data} initialTab={settingsTab} onViewShare={onViewShare} onClose={() => setModal(null)} onSave={saveSettings} commit={commit} onOpen={open} onTest={(e: Schedule) => { setModal(null); setEditor(e); }} toast={setToast}/>}
 {toast && <div className="toast" role="status"><Check size={17}/>{toast}<button className="icon-button" aria-label="안내 닫기" onClick={() => setToast('')}><X size={15}/></button></div>}
 </div>;
}

