import { useEffect, useRef, useState, type ReactNode } from 'react';
import { X, Plus, Trash2, Link2, CheckSquare, ChevronDown } from 'lucide-react';
import { blankTask, CATEGORIES, STATUSES, TYPES, REMINDERS, safeLink, uid, validateEvent, type Data, type Schedule, type Task } from './model';
export function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const d = ref.current!; d.showModal(); return () => d.close(); }, []); return <dialog ref={ref} className={'modal ' + (wide ? 'wide' : '')} onCancel={e => { e.preventDefault(); onClose(); }} aria-label={title}><div className="modal-heading"><h2>{title}</h2><button type="button" className="icon-button" aria-label="닫기" onClick={onClose}><X size={20}/></button></div>{children}</dialog>; }
export function Editor({ data, event, onSave, onClose }: { data: Data; event: Schedule; onSave: (event: Schedule, task: Task) => Promise<boolean>; onClose: () => void }) {
  const existing = data.events.some(e => e.id === event.id); const [draft, setDraft] = useState({ ...event }); const [task, setTask] = useState<Task>(() => structuredClone(data.tasks.find(t => t.id === event.taskId) || blankTask())); const [advanced, setAdvanced] = useState(existing || !!event.taskId || event.reminders.length > 0); const [error, setError] = useState(''); const [dirty, setDirty] = useState(false); const [discard, setDiscard] = useState(false); const [saving, setSaving] = useState(false); const originalEvent = useRef(data.events.find(e => e.id === event.id)); const originalTask = useRef(data.tasks.find(t => t.id === event.taskId));
  const update = (values: Partial<Schedule>) => { setDirty(true); setDraft(prev => ({ ...prev, ...values })); };
  const changeTask = (values: Partial<Task>) => { setDirty(true); setTask(prev => ({ ...prev, ...values })); };
  const close = () => saving ? undefined : dirty ? setDiscard(true) : onClose();
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (saving) return; if (JSON.stringify(originalEvent.current) !== JSON.stringify(data.events.find(e => e.id === event.id)) || JSON.stringify(originalTask.current) !== JSON.stringify(data.tasks.find(t => t.id === draft.taskId))) { setError('편집 중 다른 기기나 창에서 이 일정 또는 업무를 변경했습니다. 입력 내용을 복사한 뒤 편집창을 다시 열어 최신 내용을 확인해 주세요.'); return; } const problem = validateEvent(draft); if (problem) { setError(problem); return; } if (task.links.some(l => !l.name.trim() || !safeLink(l.url))) { setError('자료 링크의 표시 이름과 주소를 확인해 주세요. https: 또는 onenote: 주소만 저장할 수 있습니다.'); setAdvanced(true); return; } if (task.checklist.some(c => !c.text.trim())) { setError('준비할 일을 입력하거나 빈 항목을 삭제해 주세요.'); return; } const t = { ...task, name: task.name.trim() || draft.title.trim() }; setSaving(true); try { if (await onSave({ ...draft, title: draft.title.trim(), taskId: t.id }, t)) onClose(); else setError('저장하지 못했습니다. 입력 내용은 유지됩니다. 연결·권한 또는 다른 기기의 변경을 확인해 주세요.'); } finally { setSaving(false); } };
  return <Modal title={existing ? '일정 수정' : '새 일정'} onClose={close} wide><form onSubmit={submit}><fieldset disabled={saving} className="editor-fields"><div className="form-body"><label className="field">일정명 <input autoFocus value={draft.title} maxLength={300} placeholder="어떤 업무가 있나요?" onChange={e => update({ title: e.currentTarget.value })}/></label><div className="field-row"><label className="field">시작일<input type="date" min="1900-01-01" max="2200-12-31" value={draft.start} onInput={e => { const start = e.currentTarget.value; update({ start, end: draft.start === draft.end ? start : draft.end }); }}/></label><label className="field">종료일 <input type="date" min="1900-01-01" max="2200-12-31" value={draft.end} onInput={e => update({ end: e.currentTarget.value })}/></label></div><p className="help">종료일까지 포함해서 달력에 표시합니다.</p><button type="button" className="advanced-toggle" onClick={() => setAdvanced(!advanced)} aria-expanded={advanced}><ChevronDown size={17} className={advanced ? 'rotate' : ''}/>추가 옵션 {advanced ? '접기' : '펼치기'}<span>시간 · 업무 연결 · 자료 · 알림</span></button>{advanced && <>
    <div className="field-row"><label className="field">일정 유형<select aria-label="일정 유형" value={draft.type} onChange={e => update({ type: e.currentTarget.value as Schedule['type'], reminderBase: e.currentTarget.value === '마감' ? 'end' : 'start' })}>{TYPES.map(t => <option key={t}>{t}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={draft.allDay} onChange={e => update({ allDay: e.target.checked })}/>종일 일정</label></div>{!draft.allDay && <div className="field-row"><label className="field">시작 시간<input type="time" value={draft.startTime} onInput={e => update({ startTime: e.currentTarget.value })}/></label><label className="field">종료 시간<input type="time" value={draft.endTime} onInput={e => update({ endTime: e.currentTarget.value })}/></label></div>}
    <section className="form-section"><h3>업무와 연결</h3><label className="field">연결된 업무<select aria-label="연결된 업무" value={draft.taskId} onChange={e => { update({ taskId: e.currentTarget.value }); originalTask.current = data.tasks.find(t => t.id === e.currentTarget.value); setTask(structuredClone(originalTask.current || blankTask())); }}><option value="">새 업무로 저장 (이름 생략 가능)</option>{data.tasks.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">업무명<input value={task.name} maxLength={300} placeholder="비워 두면 일정명으로 저장됩니다" onChange={e => changeTask({ name: e.currentTarget.value })}/></label>{draft.taskId && <p className="help purple-text">아래 정보는 이 업무의 모든 연결 일정에 함께 적용됩니다.</p>}<div className="field-row"><label className="field">분류<select aria-label="분류" value={task.category} onChange={e => changeTask({ category: e.currentTarget.value as Task['category'] })}>{CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label><label className="field">업무 상태<select aria-label="업무 상태" value={task.status} onChange={e => changeTask({ status: e.currentTarget.value as Task['status'] })}>{STATUSES.map(c => <option key={c}>{c}</option>)}</select></label></div><label className="field">메모<textarea aria-label="메모" rows={4} maxLength={10000} placeholder="공문에서 확인할 내용, 처리 방법 등을 적어 두세요" value={task.memo} onChange={e => changeTask({ memo: e.currentTarget.value })}/></label></section>
    <section className="form-section"><h3><Link2 size={17}/>관련 자료</h3>{task.links.map((l, i) => <div className="link-edit" key={l.id}><div><input aria-label={`링크 ${i + 1} 표시 이름`} placeholder="표시 이름" maxLength={300} value={l.name} onChange={e => changeTask({ links: task.links.map(x => x.id === l.id ? { ...x, name: e.currentTarget.value } : x) })}/><input aria-label={`링크 ${i + 1} 주소`} placeholder="https:// 또는 onenote:" maxLength={10000} value={l.url} onChange={e => changeTask({ links: task.links.map(x => x.id === l.id ? { ...x, url: e.currentTarget.value } : x) })}/></div><button type="button" className="icon-button" aria-label={`링크 ${i + 1} 삭제`} onClick={() => changeTask({ links: task.links.filter(x => x.id !== l.id) })}><Trash2 size={16}/></button></div>)}<button type="button" className="text-button" onClick={() => changeTask({ links: [...task.links, { id: uid(), name: '', url: '' }] })}><Plus size={16}/>링크 추가</button><p className="help">원노트에서 ‘단락 링크 복사’ 후 원래 주소 전체를 붙여 넣으세요.</p><p className="help">원노트 설치 및 접근 권한에 따라 열리는 방식이 달라질 수 있습니다</p></section>
    <section className="form-section"><h3><CheckSquare size={17}/>준비할 일</h3>{task.checklist.map((c, i) => <div className="check-edit" key={c.id}><input type="checkbox" aria-label={`준비 ${i + 1} 완료`} checked={c.done} onChange={e => changeTask({ checklist: task.checklist.map(x => x.id === c.id ? { ...x, done: e.target.checked } : x) })}/><input aria-label={`준비 ${i + 1} 내용`} maxLength={1000} value={c.text} placeholder="준비할 일" onChange={e => changeTask({ checklist: task.checklist.map(x => x.id === c.id ? { ...x, text: e.currentTarget.value } : x) })}/><button type="button" className="icon-button" aria-label={`준비 ${i + 1} 삭제`} onClick={() => changeTask({ checklist: task.checklist.filter(x => x.id !== c.id) })}><Trash2 size={16}/></button></div>)}<button type="button" className="text-button" onClick={() => changeTask({ checklist: [...task.checklist, { id: uid(), text: '', done: false }] })}><Plus size={16}/>준비할 일 추가</button></section>
    <section className="form-section"><h3>알림</h3><label className="field">알림 기준<select aria-label="알림 기준" value={draft.reminderBase} onChange={e => update({ reminderBase: e.currentTarget.value as 'start' | 'end' })}><option value="start">일정 시작</option><option value="end">일정 종료 / 마감</option></select></label><div className="reminder-options">{REMINDERS.map(r => <label key={r.value}><input type="checkbox" checked={draft.reminders.includes(r.value)} onChange={() => update({ reminders: draft.reminders.includes(r.value) ? draft.reminders.filter(x => x !== r.value) : [...draft.reminders, r.value] })}/>{r.label}</label>)}</div><p className="help">서울 시간 기준 · 종일 일정은 시작일 09:00 / 종료일 23:59 기준입니다.<br/>저장 시 이미 지난 알림 시각은 새로 발송하지 않습니다.</p></section></>}{error && <p className="form-error" role="alert">{error}</p>}</div></fieldset><div className="modal-actions"><button type="button" disabled={saving} onClick={close}>취소</button><button className="primary" type="submit" disabled={saving}>{saving ? '저장 중…' : existing ? '변경 저장' : '일정 저장'}</button></div></form>{discard && <div className="discard-box" role="alert"><p>저장하지 않은 변경 사항을 버릴까요?</p><button type="button" onClick={() => setDiscard(false)}>계속 작성</button><button type="button" onClick={onClose}>변경 버리기</button></div>}</Modal>;
}



