import { useEffect, useRef, useState } from 'react';
import { CalendarDays, Plus, Bell, Download, X, Pencil, Trash2, Clock3, Link2, ExternalLink, Copy, Check, CheckSquare, FileText, Upload, ArrowUpRight } from 'lucide-react';
import { CATEGORIES, REMINDERS, STATUSES, blankEvent, dateLabel, deadlineLabel, seoulToday, type Data, type Schedule, type Task } from './model';
import { parseBackup } from './storage';
import { Modal } from './Editor';
type Commit = (data: Data, recovery?: boolean) => Promise<boolean>;
export function DetailPanel({ event, task, related, now, onClose, onEdit, onTask, onDelete, onOpen, onAdd, toast }: { event: Schedule; task: Task; related: Schedule[]; now: number; onClose: () => void; onEdit: () => void; onTask: (task: Task) => void; onDelete: (type: 'event' | 'task') => void; onOpen: (id: string) => void; onAdd: () => void; toast: (message: string) => void }) {
 const ref = useRef<HTMLElement>(null); const closeRef = useRef(onClose); closeRef.current = onClose;
 useEffect(() => { ref.current?.focus({ preventScroll: true }); const key = (e: KeyboardEvent) => { if (document.querySelector('dialog[open]')) return; if (e.key === 'Escape') closeRef.current(); if (e.key === 'Tab' && window.innerWidth < 1000 && ref.current) { const controls = [...ref.current.querySelectorAll<HTMLElement>('button,a,select,input')]; if (e.shiftKey && document.activeElement === controls[0]) { e.preventDefault(); controls.at(-1)?.focus(); } else if (!e.shiftKey && document.activeElement === controls.at(-1)) { e.preventDefault(); controls[0]?.focus(); } } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [event.id]);
 return <aside className="detail-panel" tabIndex={-1} ref={ref} aria-label="일정 상세"><div className="detail-top"><span>일정 상세</span><button className="icon-button" aria-label="상세 닫기" onClick={onClose}><X size={20}/></button></div><div className="detail-body"><div className="detail-tags"><span className={`tag cat-${CATEGORIES.indexOf(task.category)}`}>{task.category}</span><span className="plain-tag">{event.type}</span>{task.status === '완료' ? <span className="done-label">✓ 완료</span> : event.type === '마감' && <span className="deadline-badge">{deadlineLabel(event, seoulToday(new Date(now)), now)}</span>}</div><h2>{event.title}</h2><div className="detail-date"><CalendarDays size={17}/><span>{dateLabel(event.start)}{event.start !== event.end ? ` – ${dateLabel(event.end)} (종료일 포함)` : ''}<small>{event.allDay ? '종일' : `${event.startTime} – ${event.endTime}`} · 서울 시간</small></span></div><div className="detail-buttons"><button onClick={onEdit}><Pencil size={15}/>수정</button><button className={task.status === '완료' ? '' : 'primary'} onClick={() => onTask({ ...task, status: task.status === '완료' ? '진행 중' : '완료' })}><Check size={16}/>{task.status === '완료' ? '완료 취소' : '업무 완료'}</button><button className="icon-button danger" aria-label="일정 삭제" onClick={() => onDelete('event')}><Trash2 size={17}/></button></div>
 <section className="task-card"><div className="section-eyebrow">연결된 업무 · 공통 정보</div><h3>{task.name}</h3><label className="status-select">상태<select aria-label="업무 상태" value={task.status} onChange={e => onTask({ ...task, status: e.target.value as Task['status'] })}>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></label><p>이 업무의 {related.length}개 일정이 자료와 준비 사항을 공유합니다.</p></section>
 <section className="detail-section"><h3><CheckSquare size={17}/>준비할 일<span className="section-count">{task.checklist.filter(c => c.done).length}/{task.checklist.length}</span></h3>{task.checklist.length ? task.checklist.map(c => <label className={'check-item ' + (c.done ? 'checked' : '')} key={c.id}><input type="checkbox" checked={c.done} onChange={e => onTask({ ...task, checklist: task.checklist.map(x => x.id === c.id ? { ...x, done: e.target.checked } : x) })}/><span>{c.text}</span></label>) : <p className="help">준비할 일을 추가해 업무를 놓치지 마세요.</p>}<button className="text-button" onClick={onEdit}><Plus size={15}/>준비 사항 편집</button></section>
 <section className="detail-section"><h3><Link2 size={17}/>관련 자료</h3>{task.links.map(l => <div className="resource-link" key={l.id}><a href={l.url} target={l.url.toLowerCase().startsWith('https:') ? '_blank' : undefined} rel="noopener noreferrer" title={l.url}><span className="resource-icon"><FileText size={17}/></span><span>{l.name}<small>{l.url.toLowerCase().startsWith('onenote:') ? '원노트 단락 링크' : '웹 링크'}</small></span><ExternalLink size={15}/></a><button className="icon-button" aria-label={`${l.name} 주소 복사`} onClick={async () => { try { await navigator.clipboard.writeText(l.url); toast('원래 주소를 복사했습니다.'); } catch { toast('주소 복사를 지원하지 않습니다. 일정 수정에서 주소를 선택해 복사해 주세요.'); } }}><Copy size={15}/></button></div>)}{!task.links.length && <p className="help">원노트 ‘단락 링크 복사’로 복사한 주소를 추가하세요.</p>}<button className="text-button" onClick={onEdit}><Plus size={15}/>자료 링크 편집</button><p className="help">원노트 설치 및 접근 권한에 따라 열리는 방식이 달라질 수 있습니다</p></section>
 <section className="detail-section"><h3><FileText size={17}/>메모</h3><p className="memo">{task.memo || '아직 작성한 메모가 없습니다.'}</p></section><section className="detail-section"><h3><CalendarDays size={17}/>연결된 일정<span className="section-count">{related.length}</span></h3>{related.map(e => <button key={e.id} className={'related-event ' + (e.id === event.id ? 'selected' : '')} onClick={() => onOpen(e.id)}><span className="timeline-dot"/><span><strong>{e.title}</strong><small>{dateLabel(e.start)}{e.end !== e.start ? ` – ${dateLabel(e.end)}` : ''} · {e.type}</small></span><ArrowUpRight size={14}/></button>)}<button className="text-button" onClick={onAdd}><Plus size={15}/>이 업무에 일정 추가</button></section><section className="detail-section"><h3><Bell size={17}/>알림</h3><p className="help">{event.reminders.length ? `${event.reminderBase === 'start' ? '시작' : '종료 / 마감'} 기준 · ${REMINDERS.filter(r => event.reminders.includes(r.value)).map(r => r.label).join(', ')}` : '설정된 알림이 없습니다.'}{task.status === '완료' && ' 완료된 업무의 알림은 발송하지 않습니다.'}</p></section><button className="text-button danger" onClick={() => onDelete('task')}><Trash2 size={14}/>업무와 연결 일정 모두 삭제</button></div></aside>;
}
export function BackupDialog({ cloud = false, data, commit, onClose, toast, onImported }: { cloud?: boolean; data: Data; commit: Commit; onClose: () => void; toast: (message: string) => void; onImported: () => void }) {
 const [incoming, setIncoming] = useState<Data | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
 function exportBackup() { const blob = new Blob([JSON.stringify({ ...data, exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `업무달력-백업-${seoulToday()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); toast('전체 백업 파일을 내보냈습니다.'); }
 async function importFile(file?: File) { setError(''); setIncoming(null); if (!file) return; setLoading(true); try { if (file.size > 10 * 1024 * 1024) throw new Error('10MB 이하의 백업 파일을 선택해 주세요.'); setIncoming(parseBackup(JSON.parse(await file.text()))); } catch (e) { setError(e instanceof SyntaxError ? 'JSON 형식이 올바르지 않습니다. 기존 데이터는 그대로 보존됩니다.' : `${(e as Error).message} 기존 데이터는 그대로 보존됩니다.`); } finally { setLoading(false); } }
 return <Modal title="백업 및 가져오기" onClose={onClose}><div className="modal-content"><p>{cloud ? "같은 계정의 모든 기기가 Firebase 데이터를 공유합니다. 가져오기로 전체 교체하면 다른 기기에도 반영됩니다." : "이 버전의 데이터는 현재 브라우저에 저장되며, 다른 기기로 자동 동기화되지 않습니다."}</p><p className="help">현재 업무 {data.tasks.length}개 · 일정 {data.events.length}개 · 알림 {data.notices.length}개<br/>브라우저 데이터를 지우기 전에 백업해 주세요.</p><button className="backup-action" onClick={exportBackup}><Download size={20}/><span><strong>전체 백업 내보내기</strong><small>업무·일정·준비 사항·링크·알림을 JSON으로 저장</small></span></button><label className="file-picker"><Upload size={20}/><span>JSON 백업 파일 선택<input type="file" disabled={loading} accept=".json,application/json" aria-label="JSON 백업 파일 선택" onChange={e => { void importFile(e.target.files?.[0]); e.target.value = ''; }}/></span></label>{loading && <p role="status">백업 파일을 확인하고 있습니다.</p>}{error && <p className="form-error" role="alert">{error}</p>}{incoming && <div className="import-preview"><h3>가져올 데이터 확인</h3><p>업무 {incoming.tasks.length}개 · 일정 {incoming.events.length}개<br/>체크리스트 {incoming.tasks.reduce((n, t) => n + t.checklist.length, 0)}개 · 링크 {incoming.tasks.reduce((n, t) => n + t.links.length, 0)}개<br/>알림 {incoming.notices.length}개 · 발송 기록 {incoming.delivered.length}개</p><p>현재 데이터를 전부 교체합니다. 먼저 현재 백업을 내보내는 것을 권장합니다.</p><div className="button-row"><button onClick={() => setIncoming(null)}>취소</button><button className="primary" disabled={loading} onClick={async () => { setLoading(true); if (await commit(incoming, true)) { onImported(); onClose(); toast('백업을 가져왔습니다. 연결 관계와 알림 기록도 복원했습니다.'); } else setError('저장하지 못했습니다. 네트워크·권한·다른 기기의 변경을 확인해 주세요.'); setLoading(false); }}>확인 후 전체 교체</button></div></div>}</div></Modal>;
}
export function NotificationsDialog({ data, commit, onClose, onOpen, onTest, toast }: { data: Data; commit: Commit; onClose: () => void; onOpen: (id: string) => void; onTest: (event: Schedule) => void; toast: (message: string) => void }) {
 const [permission, setPermission] = useState(() => 'Notification' in window ? Notification.permission : 'unsupported'); const unread = data.notices.filter(n => !n.read).length;
 async function browserPermission() { if (!('Notification' in window)) { toast('이 환경은 브라우저 알림을 지원하지 않습니다. 앱 안 알림은 사용할 수 있습니다.'); return; } try { const value = await Notification.requestPermission(); setPermission(value); toast(value === 'granted' ? '브라우저 알림을 허용했습니다. 테스트 알림을 확인해 보세요.' : '브라우저 알림이 허용되지 않았습니다. 앱 안 알림은 계속 사용할 수 있습니다.'); } catch { toast('이 브라우저에서는 권한 요청을 지원하지 않습니다. 앱 안 알림을 사용해 주세요.'); } }
 function browserTest() { try { new Notification('업무달력 · 테스트 알림', { body: '브라우저 알림 테스트입니다.', tag: 'work-calendar-test' }); toast('브라우저에 테스트 알림을 요청했습니다.'); } catch { toast('브라우저 알림을 표시할 수 없습니다. 앱 안 알림은 사용할 수 있습니다.'); } }
 function scheduleTest() { const at = new Date(Math.ceil((Date.now() + 60000) / 60000) * 60000); const date = seoulToday(at); const time = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Seoul', hour: '2-digit', minute: '2-digit', hour12: false }).format(at); onTest({ ...blankEvent(date), title: '알림 동작 확인 — 테스트', allDay: false, startTime: time, endTime: time, reminders: [0] }); }
 return <Modal title="알림 및 설정" onClose={onClose}><div className="modal-content"><div className="notice-help"><Clock3 size={20}/><p>이번 버전은 앱 실행 중 알림을 확인할 수 있습니다. 앱을 닫은 상태의 예약 알림은 후속 버전에서 지원합니다</p></div><p className="help">다시 열면 놓친 알림을 목록에 모아 보여 드립니다. 브라우저 종료·기기 절전 중에는 정시 알림을 보장하지 않습니다.</p><div className="permission-box"><span>브라우저 알림 · <strong>{permission === 'granted' ? '허용됨' : permission === 'denied' ? '차단됨' : permission === 'unsupported' ? '지원되지 않음' : '허용 전'}</strong></span><div className="button-row">{permission === 'default' && <button onClick={browserPermission}>브라우저 알림 허용</button>}{permission === 'granted' && <button onClick={browserTest}>테스트 알림 보내기</button>}<button onClick={scheduleTest}>1분 뒤 앱 알림 테스트</button></div>{permission === 'denied' && <p className="help">브라우저 사이트 설정에서 알림 권한을 변경할 수 있습니다. 앱 안 알림은 계속 표시됩니다.</p>}<p className="help">테스트 일정을 저장하면 다음 분 단위 시각(1~2분 후)에 알림이 도착합니다.</p></div><div className="notice-list-title"><h3>알림 목록 <span>{unread}개 미확인</span></h3><button className="text-button" disabled={!unread} onClick={() => commit({ ...data, notices: data.notices.map(n => ({ ...n, read: true })) })}>모두 확인</button></div>{data.notices.length ? <div className="notice-list">{data.notices.slice().sort((a, b) => b.dueAt - a.dueAt).map(n => <div className={'notice-item ' + (n.read ? 'read' : '')} key={n.id}><Bell size={17}/><button onClick={async () => { if (await commit({ ...data, notices: data.notices.map(x => x.id === n.id ? { ...x, read: true } : x) })) { onClose(); onOpen(n.eventId); } }}><strong>{n.title}</strong><small>{new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', dateStyle: 'medium', timeStyle: 'short' }).format(n.dueAt)} · {n.read ? '확인함' : '미확인'}</small></button>{!n.read && <button className="icon-button" aria-label={`${n.title} 확인`} onClick={() => commit({ ...data, notices: data.notices.map(x => x.id === n.id ? { ...x, read: true } : x) })}><Check size={16}/></button>}</div>)}</div> : <div className="empty-notices"><Bell size={26}/><p>아직 도착한 알림이 없습니다.</p><small>일정 수정에서 여러 알림을 선택할 수 있습니다.</small></div>}</div></Modal>;
}

