import { useState } from 'react';
import { Bell, Download, Clock3, Check, Upload } from 'lucide-react';
import { blankEvent, seoulToday, type Data, type Schedule } from './model';
import { parseBackup } from './storage';
import { Modal } from './Editor';
type Commit = (data: Data, recovery?: boolean) => Promise<boolean>;
export function BackupDialog({ cloud = false, data, commit, onClose, toast, onImported }: { cloud?: boolean; data: Data; commit: Commit; onClose: () => void; toast: (message: string) => void; onImported: () => void }) {
 const [incoming, setIncoming] = useState<Data | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
 function exportBackup() { const blob = new Blob([JSON.stringify({ ...data, exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `업무달력-백업-${seoulToday()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); toast('전체 백업 파일을 내보냈습니다.'); }
 async function importFile(file?: File) { setError(''); setIncoming(null); if (!file) return; setLoading(true); try { if (file.size > 10 * 1024 * 1024) throw new Error('10MB 이하의 백업 파일을 선택해 주세요.'); setIncoming(parseBackup(JSON.parse(await file.text()))); } catch (e) { setError(e instanceof SyntaxError ? 'JSON 형식이 올바르지 않습니다. 기존 데이터는 그대로 보존됩니다.' : `${(e as Error).message} 기존 데이터는 그대로 보존됩니다.`); } finally { setLoading(false); } }
 return <Modal title="백업 및 가져오기" onClose={onClose}><div className="modal-content"><p>{cloud ? "같은 계정의 모든 기기가 Firebase 데이터를 공유합니다. 가져오기로 전체 교체하면 다른 기기에도 반영됩니다." : "이 버전의 데이터는 현재 브라우저에 저장되며, 다른 기기로 자동 동기화되지 않습니다."}</p><p className="help">현재 업무 {data.tasks.length}개 · 일정 {data.events.length}개 · 알림 {data.notices.length}개<br/>브라우저 데이터를 지우기 전에 백업해 주세요.</p><button className="backup-action" onClick={exportBackup}><Download size={20}/><span><strong>전체 백업 내보내기</strong><small>업무·일정·준비 사항·링크·알림을 JSON으로 저장</small></span></button><label className="file-picker"><Upload size={20}/><span>JSON 백업 파일 선택<input type="file" disabled={loading} accept=".json,application/json" aria-label="JSON 백업 파일 선택" onChange={e => { void importFile(e.target.files?.[0]); e.target.value = ''; }}/></span></label>{loading && <p role="status">백업 파일을 확인하고 있습니다.</p>}{error && <p className="form-error" role="alert">{error}</p>}{incoming && <div className="import-preview"><h3>가져올 데이터 확인</h3><p>업무 {incoming.tasks.length}개 · 일정 {incoming.events.length}개<br/>체크리스트 {incoming.tasks.reduce((n, t) => n + t.checklist.length, 0)}개 · 링크 {incoming.tasks.reduce((n, t) => n + t.links.length, 0)}개<br/>알림 {incoming.notices.length}개 · 발송 기록 {incoming.delivered.length}개</p><p>현재 데이터를 전부 교체합니다. 먼저 현재 백업을 내보내는 것을 권장합니다.</p><div className="button-row"><button onClick={() => setIncoming(null)}>취소</button><button className="primary" disabled={loading} onClick={async () => { setLoading(true); if (await commit(incoming, true)) { onImported(); onClose(); toast('백업을 가져왔습니다. 연결 관계와 알림 기록도 복원했습니다.'); } else setError('저장하지 못했습니다. 네트워크·권한·다른 기기의 변경을 확인해 주세요.'); setLoading(false); }}>확인 후 전체 교체</button></div></div>}</div></Modal>;
}
export function NotificationsDialog({ data, commit, onClose, onOpen, onTest, toast }: { data: Data; commit: Commit; onClose: () => void; onOpen: (id: string) => void; onTest: (event: Schedule) => void; toast: (message: string) => void }) {
 const [permission, setPermission] = useState(() => 'Notification' in window ? Notification.permission : 'unsupported'); const unread = data.notices.filter(n => !n.read).length;
 async function browserPermission() { if (!('Notification' in window)) { toast('이 환경은 브라우저 알림을 지원하지 않습니다. 앱 안 알림은 사용할 수 있습니다.'); return; } try { const value = await Notification.requestPermission(); setPermission(value); toast(value === 'granted' ? '브라우저 알림을 허용했습니다. 테스트 알림을 확인해 보세요.' : '브라우저 알림이 허용되지 않았습니다. 앱 안 알림은 계속 사용할 수 있습니다.'); } catch { toast('이 브라우저에서는 권한 요청을 지원하지 않습니다. 앱 안 알림을 사용해 주세요.'); } }
 function browserTest() { try { new Notification('업무달력 · 테스트 알림', { body: '브라우저 알림 테스트입니다.', tag: 'work-calendar-test' }); toast('브라우저에 테스트 알림을 요청했습니다.'); } catch { toast('브라우저 알림을 표시할 수 없습니다. 앱 안 알림은 사용할 수 있습니다.'); } }
 function scheduleTest() { const at = new Date(Math.ceil((Date.now() + 60000) / 60000) * 60000); const date = seoulToday(at); const time = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Seoul', hour: '2-digit', minute: '2-digit', hour12: false }).format(at); onTest({ ...blankEvent(date), title: '알림 동작 확인 — 테스트', allDay: false, startTime: time, endTime: time, reminders: [0] }); }
 return <Modal title="알림 및 설정" onClose={onClose}><div className="modal-content"><div className="notice-help"><Clock3 size={20}/><p>이번 버전은 앱 실행 중 알림을 확인할 수 있습니다. 앱을 닫은 상태의 예약 알림은 후속 버전에서 지원합니다</p></div><p className="help">다시 열면 놓친 알림을 목록에 모아 보여 드립니다. 브라우저 종료·기기 절전 중에는 정시 알림을 보장하지 않습니다.</p><div className="permission-box"><span>브라우저 알림 · <strong>{permission === 'granted' ? '허용됨' : permission === 'denied' ? '차단됨' : permission === 'unsupported' ? '지원되지 않음' : '허용 전'}</strong></span><div className="button-row">{permission === 'default' && <button onClick={browserPermission}>브라우저 알림 허용</button>}{permission === 'granted' && <button onClick={browserTest}>테스트 알림 보내기</button>}<button onClick={scheduleTest}>1분 뒤 앱 알림 테스트</button></div>{permission === 'denied' && <p className="help">브라우저 사이트 설정에서 알림 권한을 변경할 수 있습니다. 앱 안 알림은 계속 표시됩니다.</p>}<p className="help">테스트 일정을 저장하면 다음 분 단위 시각(1~2분 후)에 알림이 도착합니다.</p></div><div className="notice-list-title"><h3>알림 목록 <span>{unread}개 미확인</span></h3><button className="text-button" disabled={!unread} onClick={() => commit({ ...data, notices: data.notices.map(n => ({ ...n, read: true })) })}>모두 확인</button></div>{data.notices.length ? <div className="notice-list">{data.notices.slice().sort((a, b) => b.dueAt - a.dueAt).map(n => <div className={'notice-item ' + (n.read ? 'read' : '')} key={n.id}><Bell size={17}/><button onClick={async () => { if (await commit({ ...data, notices: data.notices.map(x => x.id === n.id ? { ...x, read: true } : x) })) { onClose(); onOpen(n.eventId); } }}><strong>{n.title}</strong><small>{new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', dateStyle: 'medium', timeStyle: 'short' }).format(n.dueAt)} · {n.read ? '확인함' : '미확인'}</small></button>{!n.read && <button className="icon-button" aria-label={`${n.title} 확인`} onClick={() => commit({ ...data, notices: data.notices.map(x => x.id === n.id ? { ...x, read: true } : x) })}><Check size={16}/></button>}</div>)}</div> : <div className="empty-notices"><Bell size={26}/><p>아직 도착한 알림이 없습니다.</p><small>일정 수정에서 여러 알림을 선택할 수 있습니다.</small></div>}</div></Modal>;
}

